id: find_the_flaw
learningObjectives: 
- Identify which restricted pages are accessible without login and verify the issue by replicating it. 
hints:
- To know what all routes are configured, check the App.js file.  
- Navigate to each route and if you think it should be a restricted route accessible to only authenticated users, message the page name on Snack.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "So, We've identified a very concerning drop on our website. Here’s a data dump of our analytics with the recent traffic and churned users. Can you please have a look, identify the problem, and fix it?"
        delay: 2000
      - text: "Once you’ve found it, please drop me a message here and let me know what type of users are dropping - so we'll be able to understand the impact and start working on a solution."
        delay: 3500
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${userMessageText}"
          regex: mobile|android|ios|iphobe|non web
          flags: i
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Good catch! I'll let the support team know.
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Try again! I'm sure you'll figure this out.
              delay: 2500
