id: find_the_flaw
learningObjectives: 
- Identify which restricted pages are accessible without logging in.
hints:
- To see all configured routes, check the App.js file in frontend.
- Try going over each route and tell me which one you think you should restrict to authenticated users only
- Do you think adding a item should be allowed to unauthenticated users?
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Hi there, hope you're doing well."
        delay: 700
      - text: "We've received a report that users can access all pages without logging in. This is a security vulnerability that we need to address."
        delay: 1200 
      - text: "In order to help us locate and fix the issue, can you please take a look at the routes in your frontend code and let me know if you find any page that should only be accessible to logged-in users, but are currently accessible without logging in."
        delay: 2000
      - text: "Once you’ve found it, please drop me a message here with :instruction[the route name of that page.]. This will help us pinpoint the exact location of the problem and fix it quickly."
        delay: 2500
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${userMessageText}"
          regex: /editor|editor|/settings|settings
          flags: i
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Good catch! Thanks for letting us know. Our team will now investigate and keep you updated on our progress.
              delay: 3500
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: I'm sorry, but that doesn't seem to be the correct route name. 
              delay: 700
            - text: Could you please double-check and let me know the correct route name of the page you were able to access without logging in?
              delay: 2500
