id: find_the_flaw
learningObjectives: 
- Identify which restricted pages are accessible without logging in.
hints:
- To know what all routes are configured, check the App.js file.  
- Navigate to each route and if you think it should be a restricted route accessible to only authenticated users, message the page name on Snack.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Hello!! I'm Keen, one of your colleagues here at Anythink."
        delay: 700
      - text: "We've received a report that users can access all pages without logging in. This is a security vulnerability that we need to address. I need your help to find a page that should only be accessible to logged-in users, but is currently accessible without logging in?"
        delay: 2000
      - text: "Once you’ve found it, please drop me a message here and let me know the route name of that page. It will help us to investigate and fix the issue."
        delay: 2500
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${userMessageText}"
          regex: /editor|editor|/settings|settings
          flags: i
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Good catch! Thanks for letting us know. Our team will now investigate and keep you updated on our progress.
              delay: 3500
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: I'm sorry, but that doesn't seem to be the correct route name. 
              delay: 700
            - text: Could you please double-check and let me know the correct route name of the page you were able to access without logging in?
              delay: 2500
