id: find_the_flaw
learningObjectives: 
- Identify which restricted pages are accessible without login and verify the issue by replicating it. 
hints:
- To know what all routes are configured, check the App.js file.  
- Navigate to each route and if you think it should be a restricted route accessible to only authenticated users, message the page name on Snack.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "So, We've received a report that all the pages are accessible without logging in. Someone accidentally landed on a page that they think should not be accessible without authentication. Can you please have a look and find a page that you think should only be accessed by logged in users, but now its accessible without you logging in as well."
        delay: 2000
      - text: "Once you’ve found it, please drop me a message here and let me know the route name of the page you were able to access without logging in. It will help us to investigate and start working on a solution."
        delay: 3500
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${userMessageText}"
          regex: /editor|editor|/settings|settings
          flags: i
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Good catch! Thanks for letting us know, We will identify the issue and get back to you.
              delay: 1500
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Try again! I'm sure you'll figure this out.
              delay: 2500
