id: lock_the_gates
learningObjectives: 
- Update the routing and use the PrivateRoute component to protect unautherized access on restricted pages.
hints:
- Use the Private route component for settings and editor page.
- Pass createUser as props to PrivateRoute.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Excellent work! We now have a **PrivateRoute** component which we can prevent unauthenticated users from accessing restricted pages."
        delay: 2300
      - text: "Can you use **PrivateRoute** component for the **/settings** and **/editor** route."
        delay: 2400
      - text: "Make a PR once you have made the changes."
        delay: 2500
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "On it, I'll review the changes right away."
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: keen
              message: "On it, I'll review the changes right away."
          if:
            conditions:
            - conditionId: github_is_file_modified
              equals: false
              params:
                fileName: frontend/src/components/App.js
            then:
              do:
              - actionId: bot_message
                params:
                  person: keen
                  messages:
                    - text: "Umm, that doesn't look right. Did you use PrivateRoute component?"
                      delay: 1400
              - actionId: github_pr_reject
                params:
                  person: keen
                  message: "Umm, that doesn't look right. Did you use PrivateRoute component?"
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "This looks great! Just approved. Go ahead and merge."
                delay: 2000
          - actionId: github_pr_approve
            params:
              person: keen
              message: "Nailed it! Excellent job @${user.githubuser}! You can now merge the PR."
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "Make sure your fix passes all the checks, then try again please."
                delay: 3000
          - actionId: github_pr_reject
            params:
              person: keen
              message: "Looks like this code change didn’t fix the problem. Can you take a second look?"
        github_pr_merged:
          do:
          - actionId: finish_step
githubActions:
  backend:
  frontend:
    capabilities:
    - enzyme
    testFile: "use_private_route.test.js"